travis:
  secure:
    BINSTAR_TOKEN: njXKkIRUlahe5ojgZF6JFhas/OZOOKwl3zin7V3uLfZSKooHsBFds5xtva1TwJCLErNwE04wTB01RFEnePKcFMK1lyImgKoWxS6jVEKzdqwy9Rc9PiV7WVrQ6R81+AHbTjYQiRNP8/IGjL32XephleE9zMzssV32bXPeIQPbFgfUCOGvH2VkaRINzTVLCDTTEeEbMI0yW+9QQk7uoQrMvPs6k/oLdlTiK6mYjvMcfkhfm1Zl8BRObzSlEancxx+IZFOk2ZiafMqKl8taUbb0imIEUHRpcih0A8mIMFqpZq/Sift8kGnEHGXOzCSKMv0FEmj6UtSJxnAcmDl4gUCoPAblTKQa0ycQIvRpDTmVozj+4UtjC8wQQU+Ew49memeyK/RuIHqsTppKVPV0ZYRjp3vFZcUZd1AcJ1TWZWEx3jSfvHsJlbauS4oElOM7aRnDdd4e2LBhN9dmXHRrKJct7FTorzOqJ0G9ddQ/t9b237KWSH8cd2xXJ9mnsmYq4Zu2aefZnm6eXFd1Quf7SSAx5NirkrhMoeWshEb44tlRJ8+uBldmV8Z3+ObdgLH4VoY1EkRgYeYrz2/x+tSp9HuwR5+ibFYU+61M4i0qcf/7V0TFPkaOSL0jjjOo2f0vr1Rb9FRsO69tAS5/YTqCm/6oeLLULuJCcyv2SXT9AHQCwlo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
