travis:
  secure:
    BINSTAR_TOKEN: anSwgcMLPS6JQtGaigyt1S2G8Z61WVrA7ME/udY/CpiQVolu0TT0yC+MV+7TujKJfz1/J6oHNKhe7SmOwzqL0XeGTfoUHnQW3huwXzTie1RzFnwlt0OdFlPF7xqNxhdgGQ8oeDEcqFAbEFlgEr2gG/oBjwMTPdjlxL7odBst4ni/G7sGLupa6un+DDxJoNE+9buH4GIQI7QGWLaJkfrXhIxjdmWRv8Mb05To3cHOxwlwjBess/Goze7IFOmChDOgs22gA90+/qRAN2GNTEtuHQMbeFfJ0uvPWld9gFzdp2SGysMwZJOCqlFJ1OA29b/BujdnViM6iUVm3KZW/2YUbIVQ33cl1Bjkno+7ySHminw0I5zzallg/aoCBNZ9XnPTIRuRmFN8jcXITa44JVBTredAA5/+clCwH5MSgW1tPjvj9WSSMkwne6nWyDw+tPoeir9Q7NHlSgqVlVa6Wro6oaPIHNbVez3ZIbsw9/7sjaJJtzHV2SS6xxN8JtDz/vbhej8zS9XdsumOl5g5Eb8m+0SB0+IHpe57DFqRh58e2tJ9X5qyWe1b58/LEXlxIrciCQ+ch6mSPMatr2xImjcaCX707Og59lpgqX27o3onAXIYTqE+cBwuMDm3bfT5lSLbvaEyX7b1liYfJXNisGuUQ3NEpSNKvkmOrsLHFrIJzvA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
